pitaya = Restaurant.create(name: "Pitaya", address: "rue Parmentier", phone_number: "0123456789", category: "chinese")
mcdo = Restaurant.create(name: "Mcdo", address: "rue Cracra", phone_number: "0123456787", category: "chinese")
tintin = Restaurant.create(name: "Tintin", address: "rue de Milou", phone_number: "0123456765", category: "japanese")
bocamexa = Restaurant.create(name: "Bocamexa", address: "rue du Tacos", phone_number: "0673456765", category: "belgian")
superresto = Restaurant.create(name: "Superresto", address: "rue de la gloire", phone_number: "0123451234", category: "french")
